HuskTankCopDamage = HuskTankCopDamage or class(HuskCopDamage)
HuskTankCopDamage.impact_body_distance = TankCopDamage.impact_body_distance
HuskTankCopDamage._priority_bodies_ids = TankCopDamage._priority_bodies_ids
HuskTankCopDamage.seq_clbk_vizor_shatter = TankCopDamage.seq_clbk_vizor_shatter
