HuskTankMedicCopDamage = HuskTankMedicCopDamage or class(HuskMedicDamage)
HuskTankMedicCopDamage._priority_bodies_ids = HuskTankCopDamage._priority_bodies_ids
HuskTankMedicCopDamage.seq_clbk_vizor_shatter = HuskTankCopDamage.seq_clbk_vizor_shatter
