function BlackMarketTweakData:get_glove_value(glove_id, character_name, key, player_style, material_variation)
	if key == nil then
		return
	end

	glove_id = glove_id or "default"

	if glove_id == "default" then
		glove_id = self.suit_default_gloves[player_style]

		if glove_id == false then
			return false
		end
	end

	local data = self.gloves[glove_id or "default"]

	if data == nil then
		return nil
	end

	character_name = CriminalsManager.convert_old_to_new_character_workname(character_name)

	local character_value = data.characters and data.characters[character_name] and data.characters[character_name][key]

	if character_value ~= nil then
		return character_value
	end

	local tweak_value = data and data[key]

	return tweak_value
end

function BlackMarketTweakData:build_glove_list(tweak_data)
	local x_td, y_td, x_gv, y_gv, x_sn, y_sn

	local function sort_func(x, y)
		if x == "default" then
			return true
		end

		if y == "default" then
			return false
		end

		x_td = self.gloves[x]
		y_td = self.gloves[y]

		if x_td.unlocked ~= y_td.unlocked then
			return x_td.unlocked
		end

		x_gv = x_td.global_value or x_td.dlc or "normal"
		y_gv = y_td.global_value or y_td.dlc or "normal"
		x_sn = x_gv and tweak_data.lootdrop.global_values[x_gv].sort_number or 0
		y_sn = y_gv and tweak_data.lootdrop.global_values[y_gv].sort_number or 0
		x_sn = x_sn + (x_td.gv_sort_number or 0)
		y_sn = y_sn + (y_td.gv_sort_number or 0)

		if x_sn ~= y_sn then
			return x_sn < y_sn
		end

		x_sn = x_td.sort_number or 0
		y_sn = y_td.sort_number or 0

		if x_sn ~= y_sn then
			return x_sn < y_sn
		end

		return x < y
	end

	self.glove_list = table.map_keys(self.gloves, sort_func)
end

function BlackMarketTweakData:_init_gloves(tweak_data)
	local characters_female, characters_female_big, characters_male, characters_male_big = self:_get_character_groups()
	local characters_all = table.list_union(characters_female, characters_male, characters_female_big, characters_male_big)

	local function set_characters_data(glove_id, characters, data)
		self.gloves[glove_id].characters = self.gloves[glove_id].characters or {}

		for _, key in ipairs(characters) do
			self.gloves[glove_id].characters[key] = data
		end
	end

	self.gloves = {}
	self.glove_list = {}
	self.glove_adapter = {
		third_material = "units/pd2_dlc_hnd/characters/hnd_forearms/hnd_forearms_third",
		unit = "units/pd2_dlc_hnd/characters/hnd_forearms/hnd_forearms",
		character_sequence = {
			bodhi = "set_arms_male_bodhi",
			bonnie = "set_arms_female",
			chains = "set_arms_male_chains",
			chico = "set_arms_male_02",
			dallas = "set_arms_male",
			dragan = "set_arms_male",
			dragon = "set_arms_male_02",
			ecp_female = "set_arms_female",
			ecp_male = "set_arms_male",
			female_1 = "set_arms_female",
			hoxton = "set_arms_male",
			jacket = "set_arms_male",
			jimmy = "set_arms_male",
			jowi = "set_arms_male",
			joy = "set_arms_female_joy",
			max = "set_arms_male_sangres",
			myh = "set_arms_male",
			old_hoxton = "set_arms_male",
			sokol = "set_arms_male",
			sydney = "set_arms_female_sydney",
			wild = "set_arms_male",
			wolf = "set_arms_male"
		},
		player_style_exclude_list = {
			"none",
			"slaughterhouse",
			"texvest",
			"newhorizon",
			"bikervest"
		}
	}
	self.suit_default_gloves = {
		badsanta = "heist_default",
		baron = "jesterstripe",
		bikerjacket = "heist_default",
		bikervest = "heist_default",
		boss = "heist_default",
		bossflag = "heist_default",
		bthekid = "txbull",
		bullranch = "heist_default",
		bunny = "heist_default",
		cable_guy = "heist_default",
		candycane = "heist_default",
		cargocasual = "heist_default",
		cartelboss = "heist_default",
		cassidy = "txrider",
		classyske = "heist_default",
		clown = "heist_clown",
		clown_2 = "heist_default",
		continental = "continental",
		corl = "heist_default",
		cyberhoodie = "heist_default",
		cybertrench = "heist_default",
		darkprince = "devilclaws",
		desperado = "desperado",
		dgame = "heist_default",
		dodsuit = "heist_default",
		elegantscarf = "heist_default",
		elfsuit = "heist_default",
		enforcer = "heist_default",
		esport = "esport",
		fighterpilot = "heist_default",
		gangstercoat = "heist_default",
		gangzsta = "heist_default",
		general = "heist_default",
		gentleman = "heist_default",
		ghostly = "tornrags",
		gunslinger = "heist_default",
		hacksuit = "hackglove",
		highinttech = "heist_default",
		hiphop = "bonemittens",
		hippie = "rainbow_mittens",
		hitman = "heist_default",
		jail_pd2_clan = "heist_default",
		jessjames = "txrivet",
		jumpsuit = "heat",
		kungfumaster = "heist_default",
		leather = "heist_default",
		leatherfluff = "heist_default",
		lonorwa = "heist_default",
		lowinttech = "heist_default",
		mariachi = "mariatchi",
		miami = "heist_default",
		mocow = "ranchdiesel",
		moneysuit = "heist_default",
		murky_suit = "murky",
		newhorizon = "darkmat",
		nightwalker = "tasslefringe",
		overkillpunk = "heist_default",
		peacoat = "saints",
		poolrepair = "heist_default",
		puffervest = "heist_default",
		punk = "punk",
		railroad = "heist_default",
		raincoat = "heist_default",
		roclown = "roclogrip",
		rusbear = "heist_default",
		sambass = "txsuede",
		scrub = "heist_default",
		slaughterhouse = "heist_default",
		sleekygent = "beigedriver",
		sneak_suit = "sneak",
		sparkle = "heist_default",
		t800 = "heist_default",
		texvest = "heist_default",
		thug = "heist_default",
		traditional = "heist_default",
		tux = "heist_default",
		winter_suit = "sneak",
		xmas_tuxedo = "heist_default"
	}
	self.gloves.default = {}
	self.gloves.default.name_id = "bm_gloves_default"
	self.gloves.default.desc_id = "bm_gloves_default_desc"
	self.gloves.default.texture_bundle_folder = "hnd"
	self.gloves.default.unlocked = true
	self.gloves.heist_default = {}
	self.gloves.heist_default.name_id = "bm_gloves_heistwrinkled"
	self.gloves.heist_default.desc_id = "bm_gloves_heistwrinkled_desc"
	self.gloves.heist_default.texture_bundle_folder = "hnd"
	self.gloves.heist_default.gv_sort_number = -1000
	self.gloves.heist_default.unit = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled/hnd_glv_heistwrinkled"
	self.gloves.heist_default.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled/hnd_glv_heistwrinkled_third"
	self.gloves.saints = {}
	self.gloves.saints.name_id = "bm_gloves_saintsleather"
	self.gloves.saints.desc_id = "bm_gloves_saintsleather_desc"
	self.gloves.saints.texture_bundle_folder = "hnd"
	self.gloves.saints.global_value = "trd"
	self.gloves.saints.unit = "units/pd2_dlc_hnd/characters/hnd_glv_saintsleather/hnd_glv_saintsleather"
	self.gloves.saints.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_saintsleather/hnd_glv_saintsleather_third"
	self.gloves.heist_clown = {}
	self.gloves.heist_clown.name_id = "bm_gloves_heistwrinkled_purple"
	self.gloves.heist_clown.desc_id = "bm_gloves_heistwrinkled_purple_desc"
	self.gloves.heist_clown.texture_bundle_folder = "hnd"
	self.gloves.heist_clown.global_value = "trd"
	self.gloves.heist_clown.unit = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled_purple/hnd_glv_heistwrinkled_purple"
	self.gloves.heist_clown.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled_purple/hnd_glv_heistwrinkled_purple_third"
	self.gloves.heat = {}
	self.gloves.heat.name_id = "bm_gloves_heatleather"
	self.gloves.heat.desc_id = "bm_gloves_heatleather_desc"
	self.gloves.heat.texture_bundle_folder = "hnd"
	self.gloves.heat.global_value = "trd"
	self.gloves.heat.unit = "units/pd2_dlc_hnd/characters/hnd_glv_heatleather/hnd_glv_heatleather"
	self.gloves.heat.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_heatleather/hnd_glv_heatleather_third"
	self.gloves.sneak = {}
	self.gloves.sneak.name_id = "bm_gloves_sneak"
	self.gloves.sneak.desc_id = "bm_gloves_sneak_desc"
	self.gloves.sneak.texture_bundle_folder = "hnd"
	self.gloves.sneak.unit = "units/pd2_dlc_hnd/characters/hnd_glv_sneakgloves/hnd_glv_sneakgloves"
	self.gloves.sneak.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_sneakgloves/hnd_glv_sneakgloves_third"
	self.gloves.overkillpunk = {}
	self.gloves.overkillpunk.name_id = "bm_gloves_overkillpunk"
	self.gloves.overkillpunk.desc_id = "bm_gloves_overkillpunk_desc"
	self.gloves.overkillpunk.texture_bundle_folder = "in33"
	self.gloves.overkillpunk.global_value = "in33"
	self.gloves.overkillpunk.sort_number = 1
	self.gloves.overkillpunk.unit = "units/pd2_dlc_in33/characters/glv_overkillpunk/glv_overkillpunk"
	self.gloves.overkillpunk.third_material = "units/pd2_dlc_in33/characters/glv_overkillpunk/glv_overkillpunk_third"
	self.gloves.murky = {}
	self.gloves.murky.name_id = "bm_gloves_murky"
	self.gloves.murky.desc_id = "bm_gloves_murky_desc"
	self.gloves.murky.texture_bundle_folder = "hnd"
	self.gloves.murky.unit = "units/pd2_dlc_hnd/characters/hnd_glv_murkygloves/hnd_glv_murkygloves"
	self.gloves.murky.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_murkygloves/hnd_glv_murkygloves_third"
	self.gloves.mariatchi = {}
	self.gloves.mariatchi.name_id = "bm_gloves_heistwrinkled_white"
	self.gloves.mariatchi.desc_id = "bm_gloves_heistwrinkled_white_desc"
	self.gloves.mariatchi.texture_bundle_folder = "hnd"
	self.gloves.mariatchi.unit = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled_white/hnd_glv_heistwrinkled_white"
	self.gloves.mariatchi.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_heistwrinkled_white/hnd_glv_heistwrinkled_white_third"
	self.gloves.punk = {}
	self.gloves.punk.name_id = "bm_gloves_punkleather"
	self.gloves.punk.desc_id = "bm_gloves_punkleather_desc"
	self.gloves.punk.texture_bundle_folder = "hnd"
	self.gloves.punk.global_value = "mbs"
	self.gloves.punk.unit = "units/pd2_dlc_hnd/characters/hnd_glv_punkleather/hnd_glv_punkleather"
	self.gloves.punk.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_punkleather/hnd_glv_punkleather_third"
	self.gloves.desperado = {}
	self.gloves.desperado.name_id = "bm_gloves_desperadoleather"
	self.gloves.desperado.desc_id = "bm_gloves_desperadoleather_desc"
	self.gloves.desperado.texture_bundle_folder = "hnd"
	self.gloves.desperado.global_value = "mbs"
	self.gloves.desperado.unit = "units/pd2_dlc_hnd/characters/hnd_glv_desperadoleather/hnd_glv_desperadoleather"
	self.gloves.desperado.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_desperadoleather/hnd_glv_desperadoleather_third"
	self.gloves.bonemittens = {}
	self.gloves.bonemittens.name_id = "bm_gloves_bonemittens"
	self.gloves.bonemittens.desc_id = "bm_gloves_bonemittens_desc"
	self.gloves.bonemittens.texture_bundle_folder = "hnd"
	self.gloves.bonemittens.global_value = "mbs"
	self.gloves.bonemittens.unit = "units/pd2_dlc_hnd/characters/hnd_glv_bonemittens/hnd_glv_bonemittens"
	self.gloves.bonemittens.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_bonemittens/hnd_glv_bonemittens_third"
	self.gloves.rainbow_mittens = {}
	self.gloves.rainbow_mittens.name_id = "bm_gloves_rainbowmittens"
	self.gloves.rainbow_mittens.desc_id = "bm_gloves_rainbowmittens_desc"
	self.gloves.rainbow_mittens.texture_bundle_folder = "hnd"
	self.gloves.rainbow_mittens.global_value = "mbs"
	self.gloves.rainbow_mittens.unit = "units/pd2_dlc_hnd/characters/hnd_glv_rainbowmittens/hnd_glv_rainbowmittens"
	self.gloves.rainbow_mittens.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_rainbowmittens/hnd_glv_rainbowmittens_third"
	self.gloves.esport = {}
	self.gloves.esport.name_id = "bm_gloves_esport"
	self.gloves.esport.desc_id = "bm_gloves_esport_desc"
	self.gloves.esport.texture_bundle_folder = "hnd"
	self.gloves.esport.global_value = "ess"
	self.gloves.esport.unit = "units/pd2_dlc_hnd/characters/hnd_glv_esport/hnd_glv_esport"
	self.gloves.esport.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_esport/hnd_glv_esport_third"
	self.gloves.kids = {}
	self.gloves.kids.name_id = "bm_gloves_kidswool"
	self.gloves.kids.desc_id = "bm_gloves_kidswool_desc"
	self.gloves.kids.texture_bundle_folder = "gpo"
	self.gloves.kids.global_value = "pgo"
	self.gloves.kids.unit = "units/pd2_dlc_hnd/characters/hnd_glv_kidswool/hnd_glv_kidswool"
	self.gloves.kids.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_kidswool/hnd_glv_kidswool_third"
	self.gloves.driver = {}
	self.gloves.driver.name_id = "bm_gloves_driverleather"
	self.gloves.driver.desc_id = "bm_gloves_driverleather_desc"
	self.gloves.driver.texture_bundle_folder = "gpo"
	self.gloves.driver.global_value = "pgo"
	self.gloves.driver.unit = "units/pd2_dlc_hnd/characters/hnd_glv_driverleather/hnd_glv_driverleather"
	self.gloves.driver.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_driverleather/hnd_glv_driverleather_third"
	self.gloves.fancy = {}
	self.gloves.fancy.name_id = "bm_gloves_fancycloth"
	self.gloves.fancy.desc_id = "bm_gloves_fancycloth_desc"
	self.gloves.fancy.texture_bundle_folder = "gpo"
	self.gloves.fancy.global_value = "pgo"
	self.gloves.fancy.unit = "units/pd2_dlc_hnd/characters/hnd_glv_fancycloth/hnd_glv_fancycloth"
	self.gloves.fancy.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_fancycloth/hnd_glv_fancycloth_third"
	self.gloves.tactical = {}
	self.gloves.tactical.name_id = "bm_gloves_tactical"
	self.gloves.tactical.desc_id = "bm_gloves_tactical_desc"
	self.gloves.tactical.texture_bundle_folder = "gpo"
	self.gloves.tactical.global_value = "pgo"
	self.gloves.tactical.unit = "units/pd2_dlc_hnd/characters/hnd_glv_tactical/hnd_glv_tactical"
	self.gloves.tactical.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_tactical/hnd_glv_tactical_third"
	self.gloves.biker = {}
	self.gloves.biker.name_id = "bm_gloves_biker"
	self.gloves.biker.desc_id = "bm_gloves_biker_desc"
	self.gloves.biker.texture_bundle_folder = "gpo"
	self.gloves.biker.global_value = "pgo"
	self.gloves.biker.unit = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker"
	self.gloves.biker.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_third"
	self.gloves.biker_red = {}
	self.gloves.biker_red.name_id = "bm_gloves_biker_red"
	self.gloves.biker_red.desc_id = "bm_gloves_biker_red_desc"
	self.gloves.biker_red.texture_bundle_folder = "gpo"
	self.gloves.biker_red.global_value = "pgo"
	self.gloves.biker_red.unit = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_red"
	self.gloves.biker_red.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_red_third"
	self.gloves.biker_orange = {}
	self.gloves.biker_orange.name_id = "bm_gloves_biker_orange"
	self.gloves.biker_orange.desc_id = "bm_gloves_biker_orange_desc"
	self.gloves.biker_orange.texture_bundle_folder = "gpo"
	self.gloves.biker_orange.global_value = "pgo"
	self.gloves.biker_orange.unit = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_orange"
	self.gloves.biker_orange.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_orange_third"
	self.gloves.biker_blue = {}
	self.gloves.biker_blue.name_id = "bm_gloves_biker_blue"
	self.gloves.biker_blue.desc_id = "bm_gloves_biker_blue_desc"
	self.gloves.biker_blue.texture_bundle_folder = "gpo"
	self.gloves.biker_blue.global_value = "pgo"
	self.gloves.biker_blue.unit = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_blue"
	self.gloves.biker_blue.third_material = "units/pd2_dlc_hnd/characters/hnd_glv_biker/hnd_glv_biker_blue_third"
	self.gloves.continental = {}
	self.gloves.continental.name_id = "bm_gloves_continental"
	self.gloves.continental.desc_id = "bm_gloves_continental_desc"
	self.gloves.continental.texture_bundle_folder = "anv"
	self.gloves.continental.global_value = "anv"
	self.gloves.continental.unit = "units/pd2_dlc_anv/characters/anv_glv_continental/anv_glv_continental"
	self.gloves.continental.third_material = "units/pd2_dlc_anv/characters/anv_glv_continental/anv_glv_continental_third"
	self.gloves.sportsbike = {}
	self.gloves.sportsbike.name_id = "bm_gloves_sportsbike"
	self.gloves.sportsbike.desc_id = "bm_gloves_sportsbike_desc"
	self.gloves.sportsbike.texture_bundle_folder = "pgo"
	self.gloves.sportsbike.global_value = "pgo"
	self.gloves.sportsbike.unit = "units/pd2_dlc_pgo/characters/pgo_glv_sportsbike/pgo_glv_sportsbike"
	self.gloves.sportsbike.third_material = "units/pd2_dlc_pgo/characters/pgo_glv_sportsbike/pgo_glv_sportsbike_third"
	self.gloves.hockey = {}
	self.gloves.hockey.name_id = "bm_gloves_hockey"
	self.gloves.hockey.desc_id = "bm_gloves_hockey_desc"
	self.gloves.hockey.texture_bundle_folder = "pgo"
	self.gloves.hockey.global_value = "pgo"
	self.gloves.hockey.unit = "units/pd2_dlc_pgo/characters/pgo_glv_hockey/pgo_glv_hockey"
	self.gloves.hockey.third_material = "units/pd2_dlc_pgo/characters/pgo_glv_hockey/pgo_glv_hockey_third"
	self.gloves.bananabike = {}
	self.gloves.bananabike.name_id = "bm_gloves_bananabike"
	self.gloves.bananabike.desc_id = "bm_gloves_bananabike_desc"
	self.gloves.bananabike.texture_bundle_folder = "pgo"
	self.gloves.bananabike.global_value = "pgo"
	self.gloves.bananabike.unit = "units/pd2_dlc_pgo/characters/pgo_glv_bananabike/pgo_glv_bananabike"
	self.gloves.bananabike.third_material = "units/pd2_dlc_pgo/characters/pgo_glv_bananabike/pgo_glv_bananabike_third"
	self.gloves.chopper = {}
	self.gloves.chopper.name_id = "bm_gloves_chopper"
	self.gloves.chopper.desc_id = "bm_gloves_chopper_desc"
	self.gloves.chopper.texture_bundle_folder = "pgo"
	self.gloves.chopper.global_value = "pgo"
	self.gloves.chopper.unit = "units/pd2_dlc_pgo/characters/pgo_glv_chopper/pgo_glv_chopper"
	self.gloves.chopper.third_material = "units/pd2_dlc_pgo/characters/pgo_glv_chopper/pgo_glv_chopper_third"
	self.gloves.neoncity = {}
	self.gloves.neoncity.name_id = "bm_gloves_neoncity"
	self.gloves.neoncity.desc_id = "bm_gloves_neoncity_desc"
	self.gloves.neoncity.texture_bundle_folder = "inf"
	self.gloves.neoncity.global_value = "inf"
	self.gloves.neoncity.sort_number = 2
	self.gloves.neoncity.unit = "units/pd2_dlc_inf3/characters/glv_neoncity/glv_neoncity"
	self.gloves.neoncity.third_material = "units/pd2_dlc_inf3/characters/glv_neoncity/glv_neoncity_third"
	self.gloves.molten = {}
	self.gloves.molten.name_id = "bm_gloves_molten"
	self.gloves.molten.desc_id = "bm_gloves_molten_desc"
	self.gloves.molten.texture_bundle_folder = "inf"
	self.gloves.molten.global_value = "inf"
	self.gloves.molten.sort_number = 4
	self.gloves.molten.unit = "units/pd2_dlc_inf3/characters/glv_molten/glv_molten"
	self.gloves.molten.third_material = "units/pd2_dlc_inf3/characters/glv_molten/glv_molten_third"
	self.gloves.cosmos = {}
	self.gloves.cosmos.name_id = "bm_gloves_cosmos"
	self.gloves.cosmos.desc_id = "bm_gloves_cosmos_desc"
	self.gloves.cosmos.texture_bundle_folder = "inf"
	self.gloves.cosmos.global_value = "inf"
	self.gloves.cosmos.sort_number = 3
	self.gloves.cosmos.unit = "units/pd2_dlc_inf3/characters/glv_cosmos/glv_cosmos"
	self.gloves.cosmos.third_material = "units/pd2_dlc_inf3/characters/glv_cosmos/glv_cosmos_third"
	self.gloves.tiger = {}
	self.gloves.tiger.name_id = "bm_gloves_tiger"
	self.gloves.tiger.desc_id = "bm_gloves_tiger_desc"
	self.gloves.tiger.texture_bundle_folder = "inf"
	self.gloves.tiger.global_value = "inf"
	self.gloves.tiger.unit = "units/pd2_dlc_inf3/characters/glv_tiger/glv_tiger"
	self.gloves.tiger.third_material = "units/pd2_dlc_inf3/characters/glv_tiger/glv_tiger_third"
	self.gloves.wool = {}
	self.gloves.wool.name_id = "bm_gloves_wool"
	self.gloves.wool.desc_id = "bm_gloves_wool_desc"
	self.gloves.wool.texture_bundle_folder = "in31"
	self.gloves.wool.global_value = "in31"
	self.gloves.wool.sort_number = 1
	self.gloves.wool.unit = "units/pd2_dlc_in31/characters/glv_wool/glv_wool"
	self.gloves.wool.third_material = "units/pd2_dlc_in31/characters/glv_wool/glv_wool_third"
	self.gloves.silver = {}
	self.gloves.silver.name_id = "bm_gloves_silver"
	self.gloves.silver.desc_id = "bm_gloves_silver_desc"
	self.gloves.silver.texture_bundle_folder = "in31"
	self.gloves.silver.global_value = "in31"
	self.gloves.silver.sort_number = 2
	self.gloves.silver.unit = "units/pd2_dlc_in31/characters/glv_silver/glv_silver"
	self.gloves.silver.third_material = "units/pd2_dlc_in31/characters/glv_silver/glv_silver_third"
	self.gloves.redstripe = {}
	self.gloves.redstripe.name_id = "bm_gloves_tstp_redstripe"
	self.gloves.redstripe.desc_id = "bm_gloves_tstp_redstripe_desc"
	self.gloves.redstripe.texture_bundle_folder = "tstp"
	self.gloves.redstripe.global_value = "tstp"
	self.gloves.redstripe.sort_number = 1
	self.gloves.redstripe.unit = "units/pd2_dlc_tstp/characters/tstp_glv_redstripe/tstp_glv_redstripe"
	self.gloves.redstripe.third_material = "units/pd2_dlc_tstp/characters/tstp_glv_redstripe/tstp_glv_redstripe_third"
	self.gloves.flame = {}
	self.gloves.flame.name_id = "bm_gloves_tstp_flame"
	self.gloves.flame.desc_id = "bm_gloves_tstp_flame_desc"
	self.gloves.flame.texture_bundle_folder = "tstp"
	self.gloves.flame.global_value = "tstp"
	self.gloves.flame.sort_number = 2
	self.gloves.flame.unit = "units/pd2_dlc_tstp/characters/tstp_glv_flame/tstp_glv_flame"
	self.gloves.flame.third_material = "units/pd2_dlc_tstp/characters/tstp_glv_flame/tstp_glv_flame_third"
	self.gloves.reddragon = {}
	self.gloves.reddragon.name_id = "bm_gloves_tstp_reddragon"
	self.gloves.reddragon.desc_id = "bm_gloves_tstp_reddragon_desc"
	self.gloves.reddragon.texture_bundle_folder = "tstp"
	self.gloves.reddragon.global_value = "tstp"
	self.gloves.reddragon.sort_number = 3
	self.gloves.reddragon.unit = "units/pd2_dlc_tstp/characters/tstp_glv_reddragon/tstp_glv_reddragon"
	self.gloves.reddragon.third_material = "units/pd2_dlc_tstp/characters/tstp_glv_reddragon/tstp_glv_reddragon_third"
	self.gloves.blackdragon = {}
	self.gloves.blackdragon.name_id = "bm_gloves_tstp_blackdragon"
	self.gloves.blackdragon.desc_id = "bm_gloves_tstp_blackdragon_desc"
	self.gloves.blackdragon.texture_bundle_folder = "tstp"
	self.gloves.blackdragon.global_value = "tstp"
	self.gloves.blackdragon.sort_number = 4
	self.gloves.blackdragon.unit = "units/pd2_dlc_tstp/characters/tstp_glv_blackdragon/tstp_glv_blackdragon"
	self.gloves.blackdragon.third_material = "units/pd2_dlc_tstp/characters/tstp_glv_blackdragon/tstp_glv_blackdragon_third"
	self.gloves.tiger_red = {}
	self.gloves.tiger_red.name_id = "bm_gloves_tiger_red"
	self.gloves.tiger_red.desc_id = "bm_gloves_tiger_red_desc"
	self.gloves.tiger_red.texture_bundle_folder = "pda10"
	self.gloves.tiger_red.global_value = "pda10"
	self.gloves.tiger_red.sort_number = 1
	self.gloves.tiger_red.unit = "units/pd2_dlc_pda10/characters/glv_tiger_red/glv_tiger_red"
	self.gloves.tiger_red.third_material = "units/pd2_dlc_pda10/characters/glv_tiger_red/glv_tiger_red_third"
	self.gloves.tiger_neon = {}
	self.gloves.tiger_neon.name_id = "bm_gloves_tiger_neon"
	self.gloves.tiger_neon.desc_id = "bm_gloves_tiger_neon_desc"
	self.gloves.tiger_neon.texture_bundle_folder = "pda10"
	self.gloves.tiger_neon.global_value = "pda10"
	self.gloves.tiger_neon.unit = "units/pd2_dlc_pda10/characters/glv_tiger_neon/glv_tiger_neon"
	self.gloves.tiger_neon.third_material = "units/pd2_dlc_pda10/characters/glv_tiger_neon/glv_tiger_neon_third"
	self.gloves.goldnet = {}
	self.gloves.goldnet.name_id = "bm_gloves_goldnet"
	self.gloves.goldnet.desc_id = "bm_gloves_goldnet_desc"
	self.gloves.goldnet.texture_bundle_folder = "in32"
	self.gloves.goldnet.global_value = "in32"
	self.gloves.goldnet.sort_number = 1
	self.gloves.goldnet.unit = "units/pd2_dlc_in32/characters/in32_glv_goldnet/glv_goldnet"
	self.gloves.goldnet.third_material = "units/pd2_dlc_in32/characters/in32_glv_goldnet/glv_goldnet_third"
	self.gloves.postmoto = {}
	self.gloves.postmoto.name_id = "bm_gloves_postmoto"
	self.gloves.postmoto.desc_id = "bm_gloves_postmoto_desc"
	self.gloves.postmoto.texture_bundle_folder = "in32"
	self.gloves.postmoto.global_value = "in32"
	self.gloves.postmoto.sort_number = 2
	self.gloves.postmoto.unit = "units/pd2_dlc_in32/characters/in32_glv_postmoto/glv_postmoto"
	self.gloves.postmoto.third_material = "units/pd2_dlc_in32/characters/in32_glv_postmoto/glv_postmoto_third"
	self.gloves.techlow_tortoise = {}
	self.gloves.techlow_tortoise.name_id = "bm_gloves_techlow_tortoise"
	self.gloves.techlow_tortoise.desc_id = "bm_gloves_techlow_tortoise_desc"
	self.gloves.techlow_tortoise.texture_bundle_folder = "sdtp"
	self.gloves.techlow_tortoise.global_value = "sdtp"
	self.gloves.techlow_tortoise.sort_number = 1
	self.gloves.techlow_tortoise.unit = "units/pd2_dlc_sdtp/characters/glv_techlow_tortoise/glv_techlow_tortoise"
	self.gloves.techlow_tortoise.third_material = "units/pd2_dlc_sdtp/characters/glv_techlow_tortoise/glv_techlow_tortoise_third"
	self.gloves.techlow_dragon = {}
	self.gloves.techlow_dragon.name_id = "bm_gloves_techlow_dragon"
	self.gloves.techlow_dragon.desc_id = "bm_gloves_techlow_dragon_desc"
	self.gloves.techlow_dragon.texture_bundle_folder = "sdtp"
	self.gloves.techlow_dragon.global_value = "sdtp"
	self.gloves.techlow_dragon.sort_number = 1
	self.gloves.techlow_dragon.unit = "units/pd2_dlc_sdtp/characters/glv_techlow_dragon/glv_techlow_dragon"
	self.gloves.techlow_dragon.third_material = "units/pd2_dlc_sdtp/characters/glv_techlow_dragon/glv_techlow_dragon_third"
	self.gloves.techlow_tiger = {}
	self.gloves.techlow_tiger.name_id = "bm_gloves_techlow_tiger"
	self.gloves.techlow_tiger.desc_id = "bm_gloves_techlow_tiger_desc"
	self.gloves.techlow_tiger.texture_bundle_folder = "sdtp"
	self.gloves.techlow_tiger.global_value = "sdtp"
	self.gloves.techlow_tiger.sort_number = 1
	self.gloves.techlow_tiger.unit = "units/pd2_dlc_sdtp/characters/glv_techlow_tiger/glv_techlow_tiger"
	self.gloves.techlow_tiger.third_material = "units/pd2_dlc_sdtp/characters/glv_techlow_tiger/glv_techlow_tiger_third"
	self.gloves.techlow_bird = {}
	self.gloves.techlow_bird.name_id = "bm_gloves_techlow_bird"
	self.gloves.techlow_bird.desc_id = "bm_gloves_techlow_bird_desc"
	self.gloves.techlow_bird.texture_bundle_folder = "sdtp"
	self.gloves.techlow_bird.global_value = "sdtp"
	self.gloves.techlow_bird.sort_number = 1
	self.gloves.techlow_bird.unit = "units/pd2_dlc_sdtp/characters/glv_techlow_bird/glv_techlow_bird"
	self.gloves.techlow_bird.third_material = "units/pd2_dlc_sdtp/characters/glv_techlow_bird/glv_techlow_bird_third"
	self.gloves.techhigh_tiger = {}
	self.gloves.techhigh_tiger.name_id = "bm_gloves_techhigh_tiger"
	self.gloves.techhigh_tiger.desc_id = "bm_gloves_techhigh_tiger_desc"
	self.gloves.techhigh_tiger.texture_bundle_folder = "sdtp"
	self.gloves.techhigh_tiger.global_value = "sdtp"
	self.gloves.techhigh_tiger.sort_number = 1
	self.gloves.techhigh_tiger.unit = "units/pd2_dlc_sdtp/characters/glv_techhigh_tiger/glv_techhigh_tiger"
	self.gloves.techhigh_tiger.third_material = "units/pd2_dlc_sdtp/characters/glv_techhigh_tiger/glv_techhigh_tiger_third"
	self.gloves.techhigh_tortoise = {}
	self.gloves.techhigh_tortoise.name_id = "bm_gloves_techhigh_tortoise"
	self.gloves.techhigh_tortoise.desc_id = "bm_gloves_techhigh_tortoise_desc"
	self.gloves.techhigh_tortoise.texture_bundle_folder = "sdtp"
	self.gloves.techhigh_tortoise.global_value = "sdtp"
	self.gloves.techhigh_tortoise.sort_number = 1
	self.gloves.techhigh_tortoise.unit = "units/pd2_dlc_sdtp/characters/glv_techhigh_tortoise/glv_techhigh_tortoise"
	self.gloves.techhigh_tortoise.third_material = "units/pd2_dlc_sdtp/characters/glv_techhigh_tortoise/glv_techhigh_tortoise_third"
	self.gloves.techhigh_dragon = {}
	self.gloves.techhigh_dragon.name_id = "bm_gloves_techhigh_dragon"
	self.gloves.techhigh_dragon.desc_id = "bm_gloves_techhigh_dragon_desc"
	self.gloves.techhigh_dragon.texture_bundle_folder = "sdtp"
	self.gloves.techhigh_dragon.global_value = "sdtp"
	self.gloves.techhigh_dragon.sort_number = 1
	self.gloves.techhigh_dragon.unit = "units/pd2_dlc_sdtp/characters/glv_techhigh_dragon/glv_techhigh_dragon"
	self.gloves.techhigh_dragon.third_material = "units/pd2_dlc_sdtp/characters/glv_techhigh_dragon/glv_techhigh_dragon_third"
	self.gloves.techhigh_bird = {}
	self.gloves.techhigh_bird.name_id = "bm_gloves_techhigh_bird"
	self.gloves.techhigh_bird.desc_id = "bm_gloves_techhigh_bird_desc"
	self.gloves.techhigh_bird.texture_bundle_folder = "sdtp"
	self.gloves.techhigh_bird.global_value = "sdtp"
	self.gloves.techhigh_bird.sort_number = 1
	self.gloves.techhigh_bird.unit = "units/pd2_dlc_sdtp/characters/glv_techhigh_bird/glv_techhigh_bird"
	self.gloves.techhigh_bird.third_material = "units/pd2_dlc_sdtp/characters/glv_techhigh_bird/glv_techhigh_bird_third"
	self.gloves.jesterstripe = {}
	self.gloves.jesterstripe.name_id = "bm_gloves_jesterstripe"
	self.gloves.jesterstripe.desc_id = "bm_gloves_jesterstripe_desc"
	self.gloves.jesterstripe.texture_bundle_folder = "pda8"
	self.gloves.jesterstripe.global_value = "pda8"
	self.gloves.jesterstripe.sort_number = 1
	self.gloves.jesterstripe.unit = "units/pd2_dlc_pda8/characters/glv_jesterstripe/glv_jesterstripe"
	self.gloves.jesterstripe.third_material = "units/pd2_dlc_pda8/characters/glv_jesterstripe/glv_jesterstripe_third"
	self.gloves.mnk = {}
	self.gloves.mnk.name_id = "bm_gloves_mnk"
	self.gloves.mnk.desc_id = "bm_gloves_mnk_desc"
	self.gloves.mnk.texture_bundle_folder = "cctp"
	self.gloves.mnk.global_value = "cctp"
	self.gloves.mnk.sort_number = 1
	self.gloves.mnk.unit = "units/pd2_dlc_cctp/characters/glv_mnk/glv_mnk"
	self.gloves.mnk.third_material = "units/pd2_dlc_cctp/characters/glv_mnk/glv_mnk_third"
	self.gloves.mnt = {}
	self.gloves.mnt.name_id = "bm_gloves_mnt"
	self.gloves.mnt.desc_id = "bm_gloves_mnt_desc"
	self.gloves.mnt.texture_bundle_folder = "cctp"
	self.gloves.mnt.global_value = "cctp"
	self.gloves.mnt.sort_number = 1
	self.gloves.mnt.unit = "units/pd2_dlc_cctp/characters/glv_mnt/glv_mnt"
	self.gloves.mnt.third_material = "units/pd2_dlc_cctp/characters/glv_mnt/glv_mnt_third"
	self.gloves.tgr = {}
	self.gloves.tgr.name_id = "bm_gloves_tgr"
	self.gloves.tgr.desc_id = "bm_gloves_tgr_desc"
	self.gloves.tgr.texture_bundle_folder = "cctp"
	self.gloves.tgr.global_value = "cctp"
	self.gloves.tgr.sort_number = 1
	self.gloves.tgr.unit = "units/pd2_dlc_cctp/characters/glv_tgr/glv_tgr"
	self.gloves.tgr.third_material = "units/pd2_dlc_cctp/characters/glv_tgr/glv_tgr_third"
	self.gloves.vpr = {}
	self.gloves.vpr.name_id = "bm_gloves_vpr"
	self.gloves.vpr.desc_id = "bm_gloves_vpr_desc"
	self.gloves.vpr.texture_bundle_folder = "cctp"
	self.gloves.vpr.global_value = "cctp"
	self.gloves.vpr.sort_number = 1
	self.gloves.vpr.unit = "units/pd2_dlc_cctp/characters/glv_vpr/glv_vpr"
	self.gloves.vpr.third_material = "units/pd2_dlc_cctp/characters/glv_vpr/glv_vpr_third"
	self.gloves.biker_yellow_led = {}
	self.gloves.biker_yellow_led.name_id = "bm_gloves_bike_yellow_led"
	self.gloves.biker_yellow_led.desc_id = "bm_gloves_bike_yellow_led_desc"
	self.gloves.biker_yellow_led.texture_bundle_folder = "gdtp"
	self.gloves.biker_yellow_led.global_value = "gdtp"
	self.gloves.biker_yellow_led.sort_number = 1
	self.gloves.biker_yellow_led.unit = "units/pd2_dlc_gdtp/characters/glv_biker_yellow_led/glv_biker_yellow_led"
	self.gloves.biker_yellow_led.third_material = "units/pd2_dlc_gdtp/characters/glv_biker_yellow_led/glv_biker_yellow_led_third"
	self.gloves.biker_red_led = {}
	self.gloves.biker_red_led.name_id = "bm_gloves_bike_red_led"
	self.gloves.biker_red_led.desc_id = "bm_gloves_bike_red_led_desc"
	self.gloves.biker_red_led.texture_bundle_folder = "gdtp"
	self.gloves.biker_red_led.global_value = "gdtp"
	self.gloves.biker_red_led.sort_number = 1
	self.gloves.biker_red_led.unit = "units/pd2_dlc_gdtp/characters/glv_biker_red_led/glv_biker_red_led"
	self.gloves.biker_red_led.third_material = "units/pd2_dlc_gdtp/characters/glv_biker_red_led/glv_biker_red_led_third"
	self.gloves.spikeknuckle = {}
	self.gloves.spikeknuckle.name_id = "bm_gloves_spikeknuckle"
	self.gloves.spikeknuckle.desc_id = "bm_gloves_spikeknuckle_desc"
	self.gloves.spikeknuckle.texture_bundle_folder = "gdtp"
	self.gloves.spikeknuckle.global_value = "gdtp"
	self.gloves.spikeknuckle.sort_number = 1
	self.gloves.spikeknuckle.unit = "units/pd2_dlc_gdtp/characters/glv_spikeknuckle/glv_spikeknuckle"
	self.gloves.spikeknuckle.third_material = "units/pd2_dlc_gdtp/characters/glv_spikeknuckle/glv_spikeknuckle_third"
	self.gloves.dragonscale = {}
	self.gloves.dragonscale.name_id = "bm_gloves_dragonscale"
	self.gloves.dragonscale.desc_id = "bm_gloves_dragonscale_desc"
	self.gloves.dragonscale.texture_bundle_folder = "gdtp"
	self.gloves.dragonscale.global_value = "gdtp"
	self.gloves.dragonscale.sort_number = 1
	self.gloves.dragonscale.unit = "units/pd2_dlc_gdtp/characters/glv_dragonscale/glv_dragonscale"
	self.gloves.dragonscale.third_material = "units/pd2_dlc_gdtp/characters/glv_dragonscale/glv_dragonscale_third"
	self.gloves.hardwork = {}
	self.gloves.hardwork.name_id = "bm_gloves_hardwork"
	self.gloves.hardwork.desc_id = "bm_gloves_hardwork_desc"
	self.gloves.hardwork.texture_bundle_folder = "txt1"
	self.gloves.hardwork.global_value = "txt1"
	self.gloves.hardwork.sort_number = 1
	self.gloves.hardwork.unit = "units/pd2_dlc_txt1/characters/glv_hardwork/glv_hardwork"
	self.gloves.hardwork.third_material = "units/pd2_dlc_txt1/characters/glv_hardwork/glv_hardwork_third"
	self.gloves.texriding = {}
	self.gloves.texriding.name_id = "bm_gloves_texriding"
	self.gloves.texriding.desc_id = "bm_gloves_texriding_desc"
	self.gloves.texriding.texture_bundle_folder = "txt1"
	self.gloves.texriding.global_value = "txt1"
	self.gloves.texriding.sort_number = 1
	self.gloves.texriding.unit = "units/pd2_dlc_txt1/characters/glv_texriding/glv_texriding"
	self.gloves.texriding.third_material = "units/pd2_dlc_txt1/characters/glv_texriding/glv_texriding_third"
	self.gloves.blackstar = {}
	self.gloves.blackstar.name_id = "bm_gloves_blackstar"
	self.gloves.blackstar.desc_id = "bm_gloves_blackstar_desc"
	self.gloves.blackstar.texture_bundle_folder = "txt1"
	self.gloves.blackstar.global_value = "txt1"
	self.gloves.blackstar.sort_number = 1
	self.gloves.blackstar.unit = "units/pd2_dlc_txt1/characters/glv_blackstar/glv_blackstar"
	self.gloves.blackstar.third_material = "units/pd2_dlc_txt1/characters/glv_blackstar/glv_blackstar_third"
	self.gloves.workranch = {}
	self.gloves.workranch.name_id = "bm_gloves_workranch"
	self.gloves.workranch.desc_id = "bm_gloves_workranch_desc"
	self.gloves.workranch.texture_bundle_folder = "txt1"
	self.gloves.workranch.global_value = "txt1"
	self.gloves.workranch.sort_number = 1
	self.gloves.workranch.unit = "units/pd2_dlc_txt1/characters/glv_workranch/glv_workranch"
	self.gloves.workranch.third_material = "units/pd2_dlc_txt1/characters/glv_workranch/glv_workranch_third"
	self.gloves.ranchdiesel = {}
	self.gloves.ranchdiesel.name_id = "bm_gloves_ranchdiesel"
	self.gloves.ranchdiesel.desc_id = "bm_gloves_ranchdiesel_desc"
	self.gloves.ranchdiesel.texture_bundle_folder = "rat"
	self.gloves.ranchdiesel.global_value = "rat_ranchdiesel"
	self.gloves.ranchdiesel.sort_number = 1
	self.gloves.ranchdiesel.unit = "units/pd2_dlc_rat/characters/glv_ranchdiesel/glv_ranchdiesel"
	self.gloves.ranchdiesel.third_material = "units/pd2_dlc_rat/characters/glv_ranchdiesel/glv_ranchdiesel_third"
	self.gloves.darkmat = {}
	self.gloves.darkmat.name_id = "bm_gloves_darkmat"
	self.gloves.darkmat.desc_id = "bm_gloves_darkmat_desc"
	self.gloves.darkmat.texture_bundle_folder = "prim"
	self.gloves.darkmat.global_value = "prim_darkmat"
	self.gloves.darkmat.sort_number = 1
	self.gloves.darkmat.unit = "units/pd2_dlc_prim/characters/glv_darkmat/glv_darkmat"
	self.gloves.darkmat.third_material = "units/pd2_dlc_prim/characters/glv_darkmat/glv_darkmat_third"
	self.gloves.chromecross = {}
	self.gloves.chromecross.name_id = "bm_gloves_chromecross"
	self.gloves.chromecross.desc_id = "bm_gloves_chromecross_desc"
	self.gloves.chromecross.texture_bundle_folder = "txt2"
	self.gloves.chromecross.global_value = "txt2"
	self.gloves.chromecross.sort_number = 1
	self.gloves.chromecross.unit = "units/pd2_dlc_txt2/characters/glv_chromecross/glv_chromecross"
	self.gloves.chromecross.third_material = "units/pd2_dlc_txt2/characters/glv_chromecross/glv_chromecross_third"
	self.gloves.redhand = {}
	self.gloves.redhand.name_id = "bm_gloves_redhand"
	self.gloves.redhand.desc_id = "bm_gloves_redhand_desc"
	self.gloves.redhand.texture_bundle_folder = "txt2"
	self.gloves.redhand.global_value = "txt2"
	self.gloves.redhand.sort_number = 1
	self.gloves.redhand.unit = "units/pd2_dlc_txt2/characters/glv_redhand/glv_redhand"
	self.gloves.redhand.third_material = "units/pd2_dlc_txt2/characters/glv_redhand/glv_redhand_third"
	self.gloves.leatherspark = {}
	self.gloves.leatherspark.name_id = "bm_gloves_leatherspark"
	self.gloves.leatherspark.desc_id = "bm_gloves_leatherspark_desc"
	self.gloves.leatherspark.texture_bundle_folder = "pda9"
	self.gloves.leatherspark.global_value = "pda9"
	self.gloves.leatherspark.sort_number = 1
	self.gloves.leatherspark.unit = "units/pd2_dlc_pda9/characters/glv_leatherspark/glv_leatherspark"
	self.gloves.leatherspark.third_material = "units/pd2_dlc_pda9/characters/glv_leatherspark/glv_leatherspark_third"
	self.gloves.dodskull = {}
	self.gloves.dodskull.name_id = "bm_gloves_dodskull"
	self.gloves.dodskull.desc_id = "bm_gloves_dodskull_desc"
	self.gloves.dodskull.texture_bundle_folder = "tma1"
	self.gloves.dodskull.global_value = "tma1"
	self.gloves.dodskull.sort_number = 1
	self.gloves.dodskull.unit = "units/pd2_dlc_tma1/characters/glv_dodskull/glv_dodskull"
	self.gloves.dodskull.third_material = "units/pd2_dlc_tma1/characters/glv_dodskull/glv_dodskull_third"
	self.gloves.railwork = {}
	self.gloves.railwork.name_id = "bm_gloves_railwork"
	self.gloves.railwork.desc_id = "bm_gloves_railwork_desc"
	self.gloves.railwork.texture_bundle_folder = "trt"
	self.gloves.railwork.global_value = "trt_railwork"
	self.gloves.railwork.sort_number = 1
	self.gloves.railwork.unit = "units/pd2_dlc_trt/characters/glv_railwork/glv_railwork"
	self.gloves.railwork.third_material = "units/pd2_dlc_trt/characters/glv_railwork/glv_railwork_third"
	self.gloves.devilclaws = {}
	self.gloves.devilclaws.name_id = "bm_gloves_devilclaws"
	self.gloves.devilclaws.desc_id = "bm_gloves_devilclaws_desc"
	self.gloves.devilclaws.texture_bundle_folder = "h22"
	self.gloves.devilclaws.global_value = "h22_devilclaws"
	self.gloves.devilclaws.sort_number = 1
	self.gloves.devilclaws.unit = "units/pd2_dlc_h22/characters/glv_devilclaws/glv_devilclaws"
	self.gloves.devilclaws.third_material = "units/pd2_dlc_h22/characters/glv_devilclaws/glv_devilclaws_third"
	self.gloves.tasslefringe = {}
	self.gloves.tasslefringe.name_id = "bm_gloves_tasslefringe"
	self.gloves.tasslefringe.desc_id = "bm_gloves_tasslefringe_desc"
	self.gloves.tasslefringe.texture_bundle_folder = "h22"
	self.gloves.tasslefringe.global_value = "h22_tasslefringe"
	self.gloves.tasslefringe.sort_number = 1
	self.gloves.tasslefringe.unit = "units/pd2_dlc_h22/characters/glv_tasslefringe/glv_tasslefringe"
	self.gloves.tasslefringe.third_material = "units/pd2_dlc_h22/characters/glv_tasslefringe/glv_tasslefringe_third"
	self.gloves.tornrags = {}
	self.gloves.tornrags.name_id = "bm_gloves_tornrags"
	self.gloves.tornrags.desc_id = "bm_gloves_tornrags_desc"
	self.gloves.tornrags.texture_bundle_folder = "h22"
	self.gloves.tornrags.global_value = "h22_tornrags"
	self.gloves.tornrags.sort_number = 1
	self.gloves.tornrags.unit = "units/pd2_dlc_h22/characters/glv_tornrags/glv_tornrags"
	self.gloves.tornrags.third_material = "units/pd2_dlc_h22/characters/glv_tornrags/glv_tornrags_third"
	self.gloves.beigedriver = {}
	self.gloves.beigedriver.name_id = "bm_gloves_beigedriver"
	self.gloves.beigedriver.desc_id = "bm_gloves_beigedriver_desc"
	self.gloves.beigedriver.texture_bundle_folder = "cot"
	self.gloves.beigedriver.global_value = "cot_beigedriver"
	self.gloves.beigedriver.sort_number = 1
	self.gloves.beigedriver.unit = "units/pd2_dlc_cot/characters/glv_beigedriver/glv_beigedriver"
	self.gloves.beigedriver.third_material = "units/pd2_dlc_cot/characters/glv_beigedriver/glv_beigedriver_third"
	self.gloves.txbull = {}
	self.gloves.txbull.name_id = "bm_gloves_txbull"
	self.gloves.txbull.desc_id = "bm_gloves_txbull_desc"
	self.gloves.txbull.texture_bundle_folder = "txt4"
	self.gloves.txbull.global_value = "txt4"
	self.gloves.txbull.sort_number = 1
	self.gloves.txbull.unit = "units/pd2_dlc_txt4/characters/glv_txbull/glv_txbull"
	self.gloves.txbull.third_material = "units/pd2_dlc_txt4/characters/glv_txbull/glv_txbull_third"
	self.gloves.txrider = {}
	self.gloves.txrider.name_id = "bm_gloves_txrider"
	self.gloves.txrider.desc_id = "bm_gloves_txrider_desc"
	self.gloves.txrider.texture_bundle_folder = "txt4"
	self.gloves.txrider.global_value = "txt4"
	self.gloves.txrider.sort_number = 1
	self.gloves.txrider.unit = "units/pd2_dlc_txt4/characters/glv_txrider/glv_txrider"
	self.gloves.txrider.third_material = "units/pd2_dlc_txt4/characters/glv_txrider/glv_txrider_third"
	self.gloves.txrivet = {}
	self.gloves.txrivet.name_id = "bm_gloves_txrivet"
	self.gloves.txrivet.desc_id = "bm_gloves_txrivet_desc"
	self.gloves.txrivet.texture_bundle_folder = "txt4"
	self.gloves.txrivet.global_value = "txt4"
	self.gloves.txrivet.sort_number = 1
	self.gloves.txrivet.unit = "units/pd2_dlc_txt4/characters/glv_txrivet/glv_txrivet"
	self.gloves.txrivet.third_material = "units/pd2_dlc_txt4/characters/glv_txrivet/glv_txrivet_third"
	self.gloves.txsuede = {}
	self.gloves.txsuede.name_id = "bm_gloves_txsuede"
	self.gloves.txsuede.desc_id = "bm_gloves_txsuede_desc"
	self.gloves.txsuede.texture_bundle_folder = "txt4"
	self.gloves.txsuede.global_value = "txt4"
	self.gloves.txsuede.sort_number = 1
	self.gloves.txsuede.unit = "units/pd2_dlc_txt4/characters/glv_txsuede/glv_txsuede"
	self.gloves.txsuede.third_material = "units/pd2_dlc_txt4/characters/glv_txsuede/glv_txsuede_third"
	self.gloves.roclogrip = {}
	self.gloves.roclogrip.name_id = "bm_gloves_roclogrip"
	self.gloves.roclogrip.desc_id = "bm_gloves_roclogrip_desc"
	self.gloves.roclogrip.texture_bundle_folder = "dot"
	self.gloves.roclogrip.global_value = "dot_roclogrip_glv"
	self.gloves.roclogrip.sort_number = 1
	self.gloves.roclogrip.unit = "units/pd2_dlc_dot/characters/glv_roclogrip/glv_roclogrip"
	self.gloves.roclogrip.third_material = "units/pd2_dlc_dot/characters/glv_roclogrip/glv_roclogrip_third"
	self.gloves.hackglove = {}
	self.gloves.hackglove.name_id = "bm_gloves_hackglove"
	self.gloves.hackglove.desc_id = "bm_gloves_hackglove_desc"
	self.gloves.hackglove.texture_bundle_folder = "lrfo"
	self.gloves.hackglove.global_value = "lrfo"
	self.gloves.hackglove.sort_number = 1
	self.gloves.hackglove.unit = "units/pd2_dlc_lrfo/characters/glv_hackglove/glv_hackglove"
	self.gloves.hackglove.third_material = "units/pd2_dlc_lrfo/characters/glv_hackglove/glv_hackglove_third"
end
